### ISSUE TITLE
prop-types module not found error

### ISSUE THREAD

**Issue by tnrich** [diegoddox/react-redux-toastr#119]
Hey @diegoddox ,

I am getting the following errors:

```
Error in ./~/react-redux-toastr/lib/ReduxToastr.js
Module not found: 'prop-types' in /Users/tnrich/Sites/lims/node_modules/react-redux-toastr/lib

 @ ./~/react-redux-toastr/lib/ReduxToastr.js 14:17-38
...etc
```

when trying to require your library.
![image](https://cloud.githubusercontent.com/assets/2730609/24982643/406d8d7a-1f97-11e7-96d5-d978b3d87b55.png)

Am I doing something wrong or did something change? 

I'm using "react": "^15.4.2" and node v6.9.2

Thanks!

**Comment by diegoddox** [comment]
Hi @tnrich 
This is because the module `prop-types` is in the `peerDependencies`
so just run this command, `npm i --save-dev prop-types`.

This module is because `React.PropTypes` is deprecated in `v15.5`, you can read more about it [here](https://facebook.github.io/react/docs/typechecking-with-proptypes.html)

Btw sorry for that, this should be fixed in the `v6.2.4`.
