### ISSUE TITLE
Duplicate toastr message

### ISSUE THREAD

**Issue by jchapelle** [diegoddox/react-redux-toastr#212]
I'm using the famous react-boilerplate from mxstbr with react redux and sagas. 

Everything seems to work like a charm except that when I change location (go to another page), the toastr messages displayed in the previous page appears again.

The prevent duplicate option is properly setup in the ReduxToastr component.

I did activate redux logger. 
I can see that toastr/add action is disptached when calling the action toastr.success().
Then after few seconds, an action toastr/remove is dispatched.
When changing location, the toastr message appears again but no toastr/add action is dispatched.
After few seconds, I can see a toastr/remove action dispatched and the toastr message disappears.

**Comment by ShepelievD** [comment]
the same issue with `next.js`

**Comment by shadowgroundz** [comment]
Same issue too

**Comment by gangwar1** [comment]
i am also facing same issue, i have used "react-redux-toastr": "7.4.0", version.

**Comment by tevaum** [comment]
I'm having the same issue. Is there any news about this? Is there anything we can do to help getting to the root cause of the problem?

**Comment by tevaum** [comment]
After some investigation, I found a tricky behaviour when react-redux-toastr is used with react-navigation: every time we navigate, TOASTR_ADD action gets dispatched. The most interesting stuff is that it gets dispatched without the action builder (add) being called. This way, the cache lookup in the action builder is not effective.

My proposal to solve this problem is to implement a new cache mechanism that will rely upon the application generating toastr ids. That way we should identify duplicates more precisely. Also we sould not remove the ids from cache when the toastr is dismissed because of the navigation issue that react-navigation is causing. This way, even if a user navigates after the toastr is dismissed, the toastr won't be displayed again.

**Comment by tevaum** [comment]
I implemented my proposed solution and tested locally and it doesn't solve the problem. Further investigation pointed to LOCATION_CHANGED action in react-router bringing back an invalid state, with toasters that were already dismissed. So maybe redux isn't detecting a state change when a toaster is dismissed.

**Comment by diegoddox** [comment]
Thanks @tevaum for the additional details

**Comment by diegoddox** [comment]
because of inactivity I will close it but feel free to open again.

**Comment by avi-honeycomb** [comment]
I am facing this issue with 7.6.8
