### ISSUE TITLE
Confirm box is not shown in node version 6.3.1

### ISSUE THREAD

**Issue by nicomfe** [diegoddox/react-redux-toastr#56]
Ive just updated to node version 6.3.1 and the toastr confirm box stopped being displayed.
Im seeing the @ReduxToastr/confirm/SHOW action on the console but nothing happens.

node version: 6.3.1
browser: chrome 53.0.2785.143 
os: OSX 10.11.3
react-redux-toastr 3.8.5

EDIT: I can confirm the issue was introduced in 3.8.0 as the last version working is 3.7.1

**Comment by diegoddox** [comment]
Have you tried reinstall all packages?

**Comment by nicomfe** [comment]
yes, I did

**Comment by diegoddox** [comment]
What's happens if you downgrade your node?

**Comment by nicomfe** [comment]
it works with node 5.7.1

**Comment by edmelly** [comment]
I don't think this issue is related to node version, but I could be wrong.

From `3.8.x` onwards the `.confirm-holder` div is no longer given the `active` class (it's handled differently internally). I had the _old_ CSS locally, so when I updated to the `3.8.x` branch, the old styles (with `display: none;`) were still being applied and the confirmation was always hidden.

If you see the `@ReduxToastr/confirm/SHOW` event in the console, check the DOM to see if the markup is there but hidden via CSS - it sounds like you have the same problem.

Ensure you have the latest styles (http://diegoddox.github.io/react-redux-toastr/3.8/react-redux-toastr.min.css) and that the old ones aren't included. I think it's best to compile the included less files (https://github.com/diegoddox/react-redux-toastr/tree/master/src/less) rather than link to them (either on Github or locally), as you run the risk of getting out of sync like this.

@diegoddox it would be cool to add the minified compiled less files to `build` so that people don't have to include it in their build steps (internally this is the only place I use less). It's not a huge deal, but it would prevent issues like this one.

**Comment by diegoddox** [comment]
Thanks @edmelly, what you mean by include the `minified.less` file into to the `build` folder, how is this going to help?

**Comment by edmelly** [comment]
Because otherwise people have to reference a static version of the CSS (as suggested in the readme) or compile the less files themselves (incorporating it into Webpack most likely). With the former you risk running into problems if an update to `react-redux-toastr` relies on the most recent styling changes (as happened to me).

The second option is the only way to ensure that when you update you get the latest version. But there are environments where you can't use Webpack (or don't want to add yet another loader into your existing setup): in such cases, compiling `less` files (if you aren't already doing so) is a pain: it would be simpler to be able to reference the minified CSS files in `/src` (not `/build` as I said previously: you'd need to add this to your Webpack setup though).

I can create a PR that adds the minified less file if that's helpful? Using the [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin) combined with `less-loader` (which is already used), like [this](https://github.com/webpack/less-loader#source-maps). You also then get the added benefit of source map support.

**Comment by diegoddox** [comment]
True that, I've thought about that before as well.

**Comment by diegoddox** [comment]
@edmelly you do know that you have access to the `css` file that is located in the `lib/css` folder?

so you can import from that one.

ex:
`import 'react-redux-toastr/lib/css/react-redux-toastr.min.css'`

**Comment by edmelly** [comment]
@diegoddox ah - no, I thought I'd tried that and couldn't get it working. That could be a good solution, though from memory there may be additional setup required for font files when grabbing the CSS. I'll test more thoroughly: either way, this issue can most likely be closed if @nicomfe can confirm whether my fix was successful.

**Comment by nicomfe** [comment]
just tried version 3.8.5 including the css from here http://diegoddox.github.io/react-redux-toastr/3.8/react-redux-toastr.min.css and it works. So I gueess I have to figure out how to include the latest css in my build. thanks guys
